name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lisp:
          - sbcl-bin
    env:
      LISP: ${{ matrix.lisp }}
      CI_ENV: github

    steps:
      - uses: actions/checkout@v2
      - name: Cache .roswell
        id: cache-dot-roswell
        uses: actions/cache@v1
        with:
          path: ~/.roswell
          key: ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-${{ hashFiles('**/*.asd') }}
          restore-keys: |
            ${{ runner.os }}-dot-roswell-${{ matrix.lisp }}-
            ${{ runner.os }}-dot-roswell-

      - name: Install roswell
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh

      - name: Install dependencies
        shell: bash
        run: |
          ln -s $(pwd) ~/.roswell/lisp/quicklisp/local-projects/cl-braces
          ros -e '(progn (ql:register-local-projects) (uiop:quit))'
          ros -e '(progn (ql:quickload :lisp-unit2) (uiop:quit))'
          ros -e '(progn (ql:quickload :cl-braces) (uiop:quit))'

      - name: Test Compiler
        shell: bash
        run: |
          ros -e '(let (*debugger-hook*) (asdf:test-system :cl-braces/compiler))'
